name: Docker Dev Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Docker Buildx (opcional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Subir os containers do ambiente Dev usando docker compose moderno
      - name: Bring up Docker Compose (Dev)
        run: |
          docker compose down
          docker compose up -d --build
